# Generated by Django 2.2 on 2020-03-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='images/', verbose_name='تصویر')),
                ('summary', models.CharField(max_length=300, verbose_name='توضیحات')),
            ],
        ),
    ]
