# Generated by Django 2.2 on 2020-03-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('pub_date', models.DateTimeField(verbose_name='تاریخ انتشار')),
                ('body', models.TextField(verbose_name='متن')),
                ('image', models.ImageField(upload_to='images/', verbose_name='تصویر')),
            ],
        ),
    ]
